import { Injectable } from '@angular/core';
import { JSDictionary } from '../js.dictionary';

@Injectable()
export class ChampionIdToChampionNameMap {
    public mappings: JSDictionary<string, string> = new JSDictionary<string, string>();

    constructor() 
    {
        this.mappings.put("266", "Aatrox")
        this.mappings.put("412", "Thresh")
        this.mappings.put("23", "Tryndamere")
        this.mappings.put("79", "Gragas")
        this.mappings.put("69", "Cassiopeia")
        this.mappings.put("136", "Aurelion Sol")
        this.mappings.put("13", "Ryze")
        this.mappings.put("78", "Poppy")
        this.mappings.put("14", "Sion")
        this.mappings.put("1", "Annie")
        this.mappings.put("202", "Jhin")
        this.mappings.put("43", "Karma")
        this.mappings.put("111", "Nautilus")
        this.mappings.put("240", "Kled")
        this.mappings.put("99", "Lux")
        this.mappings.put("103", "Ahri")
        this.mappings.put("2", "Olaf")
        this.mappings.put("112", "Viktor")
        this.mappings.put("34", "Anivia")
        this.mappings.put("27", "Singed")
        this.mappings.put("86", "Garen")
        this.mappings.put("127", "Lissandra")
        this.mappings.put("57", "Maokai")
        this.mappings.put("25", "Morgana")
        this.mappings.put("28", "Evelynn")
        this.mappings.put("105", "Fizz")
        this.mappings.put("74", "Heimerdinger")
        this.mappings.put("238", "Zed")
        this.mappings.put("68", "Rumble")
        this.mappings.put("82", "Mordekaiser")
        this.mappings.put("37", "Sona")
        this.mappings.put("96", "Kog'Maw")
        this.mappings.put("55", "Katarina")
        this.mappings.put("117", "Lulu")
        this.mappings.put("22", "Ashe")
        this.mappings.put("30", "Karthus")
        this.mappings.put("12", "Alistar")
        this.mappings.put("122", "Darius")
        this.mappings.put("67", "Vayne")
        this.mappings.put("110", "Varus")
        this.mappings.put("77", "Udyr")
        this.mappings.put("89", "Leona")
        this.mappings.put("126", "Jayce")
        this.mappings.put("134", "Syndra")
        this.mappings.put("80", "Pantheon")
        this.mappings.put("92", "Riven")
        this.mappings.put("121", "Kha'Zix")
        this.mappings.put("42", "Corki")
        this.mappings.put("268", "Azir")
        this.mappings.put("51", "Caitlyn")
        this.mappings.put("76", "Nidalee")
        this.mappings.put("85", "Kennen")
        this.mappings.put("3", "Galio")
        this.mappings.put("45", "Veigar")
        this.mappings.put("432", "Bard")
        this.mappings.put("150", "Gnar")
        this.mappings.put("90", "Malzahar")
        this.mappings.put("104", "Graves")
        this.mappings.put("254", "Vi")
        this.mappings.put("10", "Kayle")
        this.mappings.put("39", "Irelia")
        this.mappings.put("64", "Lee Sin")
        this.mappings.put("420", "Illaoi")
        this.mappings.put("60", "Elise")
        this.mappings.put("106", "Volibear")
        this.mappings.put("20", "Nunu")
        this.mappings.put("4", "Twisted Fate")
        this.mappings.put("24", "Jax")
        this.mappings.put("102", "Shyvana")
        this.mappings.put("429", "Kalista")
        this.mappings.put("36", "Dr. Mundo")
        this.mappings.put("427", "Ivern")
        this.mappings.put("131", "Diana")
        this.mappings.put("223", "Tahm Kench")
        this.mappings.put("63", "Brand")
        this.mappings.put("113", "Sejuani")
        this.mappings.put("8", "Vladimir")
        this.mappings.put("154", "Zac")
        this.mappings.put("421", "Rek'Sai")
        this.mappings.put("133", "Quinn")
        this.mappings.put("84", "Akali")
        this.mappings.put("163", "Taliyah")
        this.mappings.put("18", "Tristana")
        this.mappings.put("120", "Hecarim")
        this.mappings.put("15", "Sivir")
        this.mappings.put("236", "Lucian")
        this.mappings.put("107", "Rengar")
        this.mappings.put("19", "Warwick")
        this.mappings.put("72", "Skarner")
        this.mappings.put("54", "Malphite")
        this.mappings.put("157", "Yasuo")
        this.mappings.put("101", "Xerath")
        this.mappings.put("17", "Teemo")
        this.mappings.put("75", "Nasus")
        this.mappings.put("58", "Renekton")
        this.mappings.put("119", "Draven")
        this.mappings.put("35", "Shaco")
        this.mappings.put("50", "Swain")
        this.mappings.put("91", "Talon")
        this.mappings.put("40", "Janna")
        this.mappings.put("115", "Ziggs")
        this.mappings.put("245", "Ekko")
        this.mappings.put("61", "Orianna")
        this.mappings.put("114", "Fiora")
        this.mappings.put("9", "Fiddlesticks")
        this.mappings.put("31", "Cho'Gath")
        this.mappings.put("33", "Rammus")
        this.mappings.put("7", "LeBlanc")
        this.mappings.put("16", "Soraka")
        this.mappings.put("26", "Zilean")
        this.mappings.put("56", "Nocturne")
        this.mappings.put("222", "Jinx")
        this.mappings.put("83", "Yorick")
        this.mappings.put("6", "Urgot")
        this.mappings.put("203", "Kindred")
        this.mappings.put("21", "Miss Fortune")
        this.mappings.put("62", "Wukong")
        this.mappings.put("53", "Blitzcrank")
        this.mappings.put("98", "Shen")
        this.mappings.put("201", "Braum")
        this.mappings.put("5", "Xin Zhao")
        this.mappings.put("29", "Twitch")
        this.mappings.put("11", "Master Yi")
        this.mappings.put("44", "Taric")
        this.mappings.put("32", "Amumu")
        this.mappings.put("41", "Gangplank")
        this.mappings.put("48", "Trundle")
        this.mappings.put("38", "Kassadin")
        this.mappings.put("161", "Vel'Koz")
        this.mappings.put("143", "Zyra")
        this.mappings.put("267", "Nami")
        this.mappings.put("59", "Jarvan IV")
        this.mappings.put("81", "Ezreal")
        this.mappings.put("555", "Pyke")
        this.mappings.put("164", "Camille")
        this.mappings.put("518", "Neeko")
        this.mappings.put("142", "Zoe")
        this.mappings.put("0", "Minion")
    }
}